version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
